import copy
import gzip
import hashlib
import json
import re
import uuid
from pathlib import Path
from xml.dom import minidom
import xml.etree.ElementTree as ET

import bpy
from mathutils import Matrix, Vector

from .constants import SPEEDTREE_101_BLANK_SPM, SPEEDTREE_101_EXTERNAL_MESH_SAMPLE, SPEEDTREE_101_MATERIAL_SAMPLE
from .materials import make_speedtree_material
from .props import speedtree_spm_targets
from .texture_paths import atlas_texture_paths


ATLAS_LEAF_SPM_GENERATOR = "Atlas Leaf Mesh Builder"
ATLAS_LEAF_COLLECTION_SCOPE_KEY = "atlas_leaf_speedtree_scope_id"


def write_speedtree_readme(export_dir, manifest):
    path = Path(export_dir) / "README_SPEEDTREE_IMPORT.md"
    mesh_count = len(manifest["meshes"])
    lines = [
        "# SpeedTree Import Notes",
        "",
        "Generated by Atlas Leaf Mesh Builder.",
        "",
        "## Contents",
        "",
        "- The target `.spm` is a SpeedTree Modeler 10.1 asset file with one named material linked to all generated leaf meshes.",
        f"- Mesh asset files: `{mesh_count}` FBX/XML entries",
        "- Materials reference the original source textures directly; no texture copies are generated.",
        "- Meshes are closed shells with the stem pivot at object origin.",
        "- FBX export uses a single material per mesh; XML assets are written when anchors are present.",
        f"- FBX mesh geometry scale: `{manifest.get('mesh_geometry_scale', 1)}`; SpeedTree Mesh asset Scale remains `1`.",
        f"- Anchor export mode: `{manifest.get('anchor_export_mode', 'OFF')}`.",
        "",
        "## Suggested SpeedTree Setup",
        "",
        "1. Open the target `.spm` in SpeedTree Modeler 10.1.",
        "2. The atlas material should already reference the original texture maps.",
        "3. The material's cutout mesh list should reference the generated asset files in `meshes/`.",
        "4. Use that material/mesh set in a Leaf Mesh generator as leaf variants.",
        "5. If SpeedTree asks to relink files, select the original source texture folder.",
        "",
        "## Texture Map Hints",
        "",
    ]
    for key, value in manifest["textures"].items():
        lines.append(f"- {key}: `{Path(value).name}`")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def speedtree_float(value):
    return f"{float(value):.7g}"


def child_number_list(node, tag, values):
    child = ET.SubElement(node, tag)
    child.text = " ".join(speedtree_float(value) for value in values) + " "
    return child


def child_int_list(node, tag, values):
    child = ET.SubElement(node, tag)
    child.text = " ".join(str(int(value)) for value in values) + " "
    return child


def object_bounds(points):
    if not points:
        return {}
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    zs = [point[2] for point in points]
    return {
        "BoundsMinX": speedtree_float(min(xs)),
        "BoundsMinY": speedtree_float(min(ys)),
        "BoundsMinZ": speedtree_float(min(zs)),
        "BoundsMaxX": speedtree_float(max(xs)),
        "BoundsMaxY": speedtree_float(max(ys)),
        "BoundsMaxZ": speedtree_float(max(zs)),
    }


def speedtree_anchor_prefix(props):
    return (getattr(props, "speedtree_anchor_prefix", "") or "anchor").lower()


def is_speedtree_anchor_empty(obj, props):
    if obj.type != "EMPTY":
        return False
    prefix = speedtree_anchor_prefix(props)
    return bool(obj.get("atlas_leaf_speedtree_anchor")) or obj.name.lower().startswith(prefix)


def source_anchor_roots(source):
    roots = []
    parent = source.parent
    if parent is not None and parent.type == "EMPTY" and parent.get("atlas_leaf_anchor_container"):
        roots.extend(parent.children)
    roots.extend(source.children)
    return roots


def collect_source_anchors(source, props, mesh_geometry_scale):
    anchors = []

    def walk(obj):
        if obj == source:
            return
        if is_speedtree_anchor_empty(obj, props):
            local_matrix = source.matrix_world.inverted() @ obj.matrix_world
            position = local_matrix.translation * mesh_geometry_scale
            rotation = local_matrix.to_quaternion()
            axis, angle = rotation.to_axis_angle()
            if abs(angle) <= 1.0e-8:
                axis = Vector((0.0, 1.0, 0.0))
            anchor_id = obj.get("speedtree_anchor_id", getattr(props, "speedtree_anchor_material_id", 0))
            anchors.append(
                {
                    "name": obj.name,
                    "position": [float(position.x), float(position.y), float(position.z)],
                    "axis": [float(axis.x), float(axis.y), float(axis.z)],
                    "angle_degrees": float(angle * 180.0 / 3.141592653589793),
                    "scale": float(getattr(props, "speedtree_anchor_scale", 1.0)),
                    "material_id": int(anchor_id),
                    "local_matrix": Matrix.Translation(position) @ rotation.to_matrix().to_4x4(),
                }
            )
        for child in obj.children:
            walk(child)

    for root in source_anchor_roots(source):
        walk(root)
    anchors.sort(key=lambda item: item["name"].lower())
    return anchors


def write_speedtree_xml_mesh(xml_path, mesh, material_name, anchors):
    mesh.calc_loop_triangles()
    uv_layer = mesh.uv_layers.active.data if mesh.uv_layers.active else None

    points = []
    normals = []
    uvs = []
    point_indices = []
    vertex_indices = []
    for triangle in mesh.loop_triangles:
        for loop_index in triangle.loops:
            vertex_index = mesh.loops[loop_index].vertex_index
            vertex = mesh.vertices[vertex_index]
            normal = mesh.loops[loop_index].normal
            uv = uv_layer[loop_index].uv if uv_layer else None
            index = len(points)
            points.append((float(vertex.co.x), float(vertex.co.y), float(vertex.co.z)))
            normals.append((float(normal.x), float(normal.y), float(normal.z)))
            uvs.append((float(uv.x), float(uv.y)) if uv else (0.0, 0.0))
            point_indices.append(index)
            vertex_indices.append(index)

    root = ET.Element(
        "SpeedTreeRaw",
        {
            "VersionMajor": "9",
            "VersionMinor": "4",
            "UserData": "Atlas Leaf Mesh Builder",
            "Source": str(xml_path),
        },
    )
    materials = ET.SubElement(root, "Materials", {"Count": "1", "FlipOpacity": "0"})
    ET.SubElement(
        materials,
        "Material",
        {
            "ID": "0",
            "Name": material_name or "AtlasLeaf_Material",
            "TwoSided": "1",
            "UserData": "",
            "VertexOpacity": "1",
            "FlipNormalsOnBackside": "1",
        },
    )
    objects = ET.SubElement(root, "Objects", {"Count": "3" if anchors else "2", **object_bounds(points)})
    ET.SubElement(objects, "Object", {"ID": "0", "Name": Path(xml_path).stem, "AbsX": "0", "AbsY": "0", "AbsZ": "0", "RelX": "0", "RelY": "0", "RelZ": "0"})
    mesh_object = ET.SubElement(
        objects,
        "Object",
        {
            "ID": "1",
            "ParentID": "0",
            "Name": Path(xml_path).stem,
            "AbsX": "0",
            "AbsY": "0",
            "AbsZ": "0",
            "RelX": "0",
            "RelY": "0",
            "RelZ": "0",
            **object_bounds(points),
        },
    )
    point_node = ET.SubElement(mesh_object, "Points", {"Count": str(len(points))})
    child_number_list(point_node, "X", [point[0] for point in points])
    child_number_list(point_node, "Y", [point[1] for point in points])
    child_number_list(point_node, "Z", [point[2] for point in points])

    vertex_node = ET.SubElement(mesh_object, "Vertices", {"Count": str(len(points))})
    child_number_list(vertex_node, "NormalX", [normal[0] for normal in normals])
    child_number_list(vertex_node, "NormalY", [normal[1] for normal in normals])
    child_number_list(vertex_node, "NormalZ", [normal[2] for normal in normals])
    child_number_list(vertex_node, "TexcoordU", [uv[0] for uv in uvs])
    child_number_list(vertex_node, "TexcoordV", [uv[1] for uv in uvs])
    child_number_list(vertex_node, "AO", [1.0] * len(points))
    child_number_list(vertex_node, "Blend", [0.0] * len(points))
    child_number_list(vertex_node, "VertexColorR", [1.0] * len(points))
    child_number_list(vertex_node, "VertexColorG", [1.0] * len(points))
    child_number_list(vertex_node, "VertexColorB", [1.0] * len(points))
    child_number_list(vertex_node, "VertexColorA", [1.0] * len(points))
    child_number_list(vertex_node, "GeometryType", [0.0] * len(points))

    triangle_node = ET.SubElement(mesh_object, "Triangles", {"Material": "0", "Count": str(len(mesh.loop_triangles))})
    child_int_list(triangle_node, "PointIndices", point_indices)
    child_int_list(triangle_node, "VertexIndices", vertex_indices)

    if anchors:
        anchor_object = ET.SubElement(
            objects,
            "Object",
            {"ID": "2", "ParentID": "0", "Name": "Anchors", "AbsX": "0", "AbsY": "0", "AbsZ": "0", "RelX": "0", "RelY": "0", "RelZ": "0"},
        )
        material_id = str(anchors[0]["material_id"])
        refs = ET.SubElement(anchor_object, "LeafReferences", {"Material": material_id, "Count": str(len(anchors))})
        child_number_list(refs, "X", [anchor["position"][0] for anchor in anchors])
        child_number_list(refs, "Y", [anchor["position"][1] for anchor in anchors])
        child_number_list(refs, "Z", [anchor["position"][2] for anchor in anchors])
        child_number_list(refs, "Scale", [anchor["scale"] for anchor in anchors])
        child_number_list(refs, "RotAxisX", [anchor["axis"][0] for anchor in anchors])
        child_number_list(refs, "RotAxisY", [anchor["axis"][1] for anchor in anchors])
        child_number_list(refs, "RotAxisZ", [anchor["axis"][2] for anchor in anchors])
        child_number_list(refs, "RotAngle", [anchor["angle_degrees"] for anchor in anchors])
        child_int_list(refs, "MeshID", [0] * len(anchors))
        child_int_list(refs, "MeshLOD", [0] * len(anchors))
        child_number_list(refs, "VertexColorR", [1.0] * len(anchors))
        child_number_list(refs, "VertexColorG", [1.0] * len(anchors))
        child_number_list(refs, "VertexColorB", [1.0] * len(anchors))

    rough = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(rough).toprettyxml(indent="\t", encoding="UTF-8")
    Path(xml_path).write_bytes(pretty)
    return xml_path


def read_spm_xml(path):
    return ET.fromstring(gzip.decompress(Path(path).read_bytes()))


def write_spm_xml(path, root):
    rough = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(rough).toprettyxml(indent="\t", encoding="UTF-8")
    Path(path).write_bytes(gzip.compress(pretty, mtime=0))


def relative_spm_path(spm_path, target_path):
    rel = Path(target_path).resolve()
    try:
        import os

        rel_text = os.path.relpath(str(rel), str(Path(spm_path).resolve().parent))
    except ValueError:
        rel_text = str(rel)
    return rel_text.replace("\\", "/")


def child_text(node, tag, value):
    child = node.find(tag)
    if child is None:
        child = ET.SubElement(node, tag)
    child.text = str(value)
    return child


def spm_export_scope(manifest):
    return str(manifest.get("export_scope_id") or manifest.get("source_collection") or "AtlasLeaf")


def manifests_share_export_scope(manifest, previous_manifest):
    if not isinstance(manifest, dict) or not isinstance(previous_manifest, dict):
        return False
    current_id = manifest.get("export_scope_id")
    previous_id = previous_manifest.get("export_scope_id")
    return bool(current_id and previous_id and str(current_id) == str(previous_id))


def scope_manifest_filename(scope_id):
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(scope_id)).strip("._")
    return f"{text or 'AtlasLeaf'}.json"


def target_manifest_key(target_spm):
    if not target_spm:
        return ""
    return sanitize_filename_component(Path(target_spm).stem, "target")


def scope_manifest_path(export_dir, manifest, target_spm=None):
    filename = scope_manifest_filename(spm_export_scope(manifest))
    target_key = target_manifest_key(target_spm)
    if target_key:
        filename = f"{Path(filename).stem}__{target_key}.json"
    return Path(export_dir) / ".atlas_leaf_speedtree_scopes" / filename


def previous_scope_manifest(export_dir, manifest, fallback_manifest=None, target_spm=None):
    scoped_manifest = read_json_file(scope_manifest_path(export_dir, manifest, target_spm), {})
    if manifests_share_export_scope(manifest, scoped_manifest):
        return scoped_manifest
    fallback_manifest = fallback_manifest or {}
    if manifests_share_export_scope(manifest, fallback_manifest):
        fallback_spm = fallback_manifest.get("spm")
        if not target_spm or not fallback_spm or blend_paths_equal(fallback_spm, target_spm):
            return fallback_manifest
    return {}


def write_scope_manifest(export_dir, manifest, target_spm=None):
    path = scope_manifest_path(export_dir, manifest, target_spm)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path


def target_manifest_path(target_spm):
    target_spm = Path(target_spm)
    filename = f"{sanitize_filename_component(target_spm.stem, 'target')}.json"
    return target_spm.parent / ".atlas_leaf_speedtree_targets" / filename


def ensure_collection_export_scope_id(collection):
    scope_id = collection.get(ATLAS_LEAF_COLLECTION_SCOPE_KEY)
    if not scope_id:
        scope_id = uuid.uuid4().hex
        collection[ATLAS_LEAF_COLLECTION_SCOPE_KEY] = scope_id
    return str(scope_id)


def blend_paths_equal(path_a, path_b):
    try:
        return Path(path_a).resolve() == Path(path_b).resolve()
    except OSError:
        return str(path_a).replace("\\", "/").lower() == str(path_b).replace("\\", "/").lower()


def texture_path_signature(texture_exports):
    payload = {
        str(key): str(value).replace("\\", "/").lower()
        for key, value in sorted((texture_exports or {}).items())
    }
    encoded = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def collection_scope_is_duplicated(collection, scope_id, existing_manifest=None):
    collections = getattr(getattr(bpy, "data", None), "collections", ())
    matches = []
    for candidate in collections:
        try:
            candidate_scope = candidate.get(ATLAS_LEAF_COLLECTION_SCOPE_KEY)
        except AttributeError:
            continue
        if candidate_scope and str(candidate_scope) == str(scope_id):
            matches.append(candidate)
    if len(matches) <= 1:
        return False

    owner_name = str((existing_manifest or {}).get("source_collection") or "")
    collection_name = str(getattr(collection, "name", "") or "")
    return not owner_name or collection_name != owner_name


def resolve_export_scope_id(collection, export_dir, texture_signature=""):
    scope_id = ensure_collection_export_scope_id(collection)
    probe = {"export_scope_id": scope_id}
    existing = read_json_file(scope_manifest_path(export_dir, probe), {})
    duplicated_collection = collection_scope_is_duplicated(collection, scope_id, existing)
    different_blend = False
    if manifests_share_export_scope(probe, existing):
        previous_blend = str(existing.get("blend_file") or "")
        current_blend = str(bpy.data.filepath or "")
        different_blend = bool(
            previous_blend and current_blend and not blend_paths_equal(previous_blend, current_blend)
        )
    if different_blend or duplicated_collection:
        # The scope id arrived here through a copied blend/collection. Claim a
        # fresh scope even when the owner manifest or original file is missing.
        # Texture changes on the owning collection are normal overwrite updates
        # and do not transfer ownership to a new atlas.
        scope_id = uuid.uuid4().hex
        collection[ATLAS_LEAF_COLLECTION_SCOPE_KEY] = scope_id
    return scope_id


def atlas_leaf_spm_user_data(manifest, kind):
    payload = {
        "generator": ATLAS_LEAF_SPM_GENERATOR,
        "scope": spm_export_scope(manifest),
        "kind": kind,
    }
    group = manifest.get("material_collection") if isinstance(manifest, dict) else None
    if group:
        payload["group"] = str(group)
    return json.dumps(payload, separators=(",", ":"), sort_keys=True)


def parse_atlas_leaf_spm_user_data(text):
    if not text:
        return {}
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return {}
    if payload.get("generator") != ATLAS_LEAF_SPM_GENERATOR:
        return {}
    return payload


def tag_spm_asset(node, manifest, kind):
    child_text(node, "UserData", atlas_leaf_spm_user_data(manifest, kind))
    return node


def make_season_control_point(x, y="1"):
    point = ET.Element("ControlPoint")
    child_text(point, "X", x)
    child_text(point, "Y", y)
    child_text(point, "TangentX", "1")
    child_text(point, "TangentY", "0")
    child_text(point, "Length", "0")
    return point


def force_material_season_curve_one(material):
    season_curve = material.find("SeasonCurve")
    if season_curve is None:
        season_curve = ET.SubElement(material, "SeasonCurve", {"DrawMode": "false"})
    season_curve.attrib["DrawMode"] = "false"
    for child in list(season_curve):
        season_curve.remove(child)
    season_curve.append(make_season_control_point("0"))
    season_curve.append(make_season_control_point("1"))

    override = material.find("OverrideSeason")
    if override is not None:
        override.text = "false"
    return season_curve


def first_material_template():
    root = read_spm_xml(SPEEDTREE_101_MATERIAL_SAMPLE)
    assets = root.find("Assets")
    if assets is None:
        raise RuntimeError("SpeedTree 10.1 material sample has no Assets node.")
    for node in assets:
        if node.tag == "Material_v8":
            return copy.deepcopy(node)
    raise RuntimeError("SpeedTree 10.1 material sample has no Material_v8 node.")


def first_external_mesh_template():
    root = read_spm_xml(SPEEDTREE_101_EXTERNAL_MESH_SAMPLE)
    assets = root.find("Assets")
    if assets is None:
        raise RuntimeError("SpeedTree 10.1 mesh sample has no Assets node.")
    for node in assets:
        if node.tag == "Mesh" and node.findtext("Embedded") == "false":
            return copy.deepcopy(node)
    raise RuntimeError("SpeedTree 10.1 mesh sample has no external Mesh node.")


def set_material_map(material, map_name, texture_path, spm_path, enabled=True):
    map_node = None
    for candidate in material.findall("Map"):
        if candidate.attrib.get("Name") == map_name:
            map_node = candidate
            break
    if map_node is None:
        return

    tex_filename = child_text(map_node, "TexFilename", "")
    if texture_path:
        tex_filename.text = relative_spm_path(spm_path, texture_path)
        child_text(map_node, "TexEnabled", "true" if enabled else "false")
        child_text(map_node, "TexSizeX", "4096")
        child_text(map_node, "TexSizeY", "4096")
    else:
        tex_filename.text = ""
        child_text(map_node, "TexEnabled", "false")


def make_spm_material(spm_path, texture_exports, mesh_ids, material_name, manifest=None):
    material = first_material_template()
    material.attrib["ID"] = "1"
    material.attrib["Name"] = material_name
    update_spm_material(material, spm_path, texture_exports, mesh_ids)
    if manifest is not None:
        tag_spm_asset(material, manifest, "material")
    return material


def update_spm_material(material, spm_path, texture_exports, mesh_ids):
    child_text(material, "TwoSided", "true")
    child_text(material, "CutoutMeshID", str(mesh_ids[0]))
    child_text(material, "Width", "4096")
    child_text(material, "Height", "4096")
    child_text(material, "Atlas", "0")
    child_text(material, "AtlasName", "")
    child_text(material, "BackMaterialID", "-1")

    supplemental = material.find("SupplementalCutoutMeshIDs")
    if supplemental is None:
        supplemental = ET.SubElement(material, "SupplementalCutoutMeshIDs")
    for child in list(supplemental):
        supplemental.remove(child)
    supplemental.attrib["Count"] = str(max(0, len(mesh_ids) - 1))
    for mesh_id in mesh_ids[1:]:
        ET.SubElement(supplemental, "CutoutMesh", {"ID": str(mesh_id)})

    set_material_map(material, "Color", texture_exports.get("albedo"), spm_path)
    set_material_map(material, "Opacity", texture_exports.get("alpha"), spm_path)
    set_material_map(material, "Normal", texture_exports.get("normal"), spm_path)
    set_material_map(material, "Gloss", texture_exports.get("gloss") or texture_exports.get("roughness"), spm_path)
    set_material_map(material, "Height", texture_exports.get("height"), spm_path)
    set_material_map(material, "SubsurfaceColor", texture_exports.get("translucency"), spm_path)
    set_material_map(material, "SubsurfaceAmount", texture_exports.get("translucency"), spm_path)
    for empty_map in ("Specular", "Metallic", "AO", "Custom", "Custom2"):
        set_material_map(material, empty_map, None, spm_path, enabled=False)
    force_material_season_curve_one(material)
    return material


def spm_material_mesh_ids(material):
    ids = []
    cutout = material.findtext("CutoutMeshID")
    if cutout and cutout != "-1":
        ids.append(int(cutout))
    supplemental = material.find("SupplementalCutoutMeshIDs")
    if supplemental is not None:
        for child in supplemental.findall("CutoutMesh"):
            mesh_id = child.attrib.get("ID")
            if mesh_id and mesh_id != "-1":
                ids.append(int(mesh_id))
    return ids


def integer_value(value):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


def positive_int(value):
    number = integer_value(value)
    return number if number is not None and number > 0 else None


def spm_generator_property_pairs(root, allowed_types=None):
    normalize_type = lambda value: re.sub(r"[^a-z0-9]+", "", str(value or "").lower())
    allowed = {normalize_type(value) for value in allowed_types} if allowed_types else None
    pairs = []
    for generator_index, generator in enumerate(root.iter("Generator")):
        generator_type = str(generator.attrib.get("Type") or generator.findtext("Type") or "").strip()
        if allowed is not None and normalize_type(generator_type) not in allowed:
            continue
        properties = generator.find("Properties")
        if properties is None:
            continue
        nodes_by_name = {}
        for prop in properties.findall("Property"):
            name = str(prop.findtext("Name") or "").strip()
            if name:
                nodes_by_name[name] = prop
        for name, material_property in nodes_by_name.items():
            if name.rsplit(":", 1)[-1].lower() != "material":
                continue
            prefix = name.rsplit(":", 1)[0]
            mesh_name = f"{prefix}:Mesh"
            mesh_property = nodes_by_name.get(mesh_name)
            pairs.append(
                {
                    "generator": generator,
                    "generator_index": generator_index,
                    "generator_name": str(generator.findtext("Name") or ""),
                    "generator_type": generator_type,
                    "slot_prefix": prefix,
                    "material_property": material_property,
                    "mesh_property": mesh_property,
                }
            )
    return pairs


def spm_generator_referenced_mesh_ids(root):
    mesh_ids = set()
    for pair in spm_generator_property_pairs(root):
        mesh_property = pair.get("mesh_property")
        if mesh_property is None:
            continue
        mesh_id = positive_int(mesh_property.findtext("Value"))
        if mesh_id is not None:
            mesh_ids.add(mesh_id)
    return mesh_ids


def spm_generator_referenced_material_ids(root):
    material_ids = set()
    for pair in spm_generator_property_pairs(root):
        material_id = positive_int(pair["material_property"].findtext("Value"))
        if material_id is not None:
            material_ids.add(material_id)
    return material_ids


def source_materials_by_name(assets, source_material_names, source_material_ids=None):
    names = []
    for value in source_material_names or []:
        name = str(value or "").strip()
        if not name:
            raise RuntimeError("Source material names cannot contain an empty value.")
        if name in names:
            raise RuntimeError(f"Source material name is duplicated: '{name}'.")
        names.append(name)
    if not names:
        raise RuntimeError("Generator connection requires at least one source material name.")

    requested_ids = {}
    if isinstance(source_material_ids, dict):
        requested_ids = {str(key): positive_int(value) for key, value in source_material_ids.items()}
    elif source_material_ids:
        if len(source_material_ids) != len(names):
            raise RuntimeError("Source material ID count does not match source material names.")
        requested_ids = {name: positive_int(value) for name, value in zip(names, source_material_ids)}

    records = {}
    for name in names:
        matches = [node for node in assets.findall("Material_v8") if node.attrib.get("Name") == name]
        if len(matches) != 1:
            raise RuntimeError(
                f"Source material '{name}' must resolve to exactly one Material_v8 asset; found {len(matches)}."
            )
        material = matches[0]
        material_id = positive_int(material.attrib.get("ID"))
        if material_id is None:
            raise RuntimeError(f"Source material '{name}' has an invalid ID.")
        requested_id = requested_ids.get(name)
        if name in requested_ids and requested_id != material_id:
            raise RuntimeError(
                f"Source material '{name}' ID is {material_id}, expected {requested_ids.get(name)}."
            )
        mesh_ids = spm_material_mesh_ids(material)
        if not mesh_ids:
            raise RuntimeError(f"Source material '{name}' has no cutout mesh IDs.")
        records[material_id] = {"name": name, "material": material, "mesh_ids": mesh_ids}
    return names, records


def atlas_output_bindings(assets, material_groups):
    materials_by_id = {positive_int(node.attrib.get("ID")): node for node in assets.findall("Material_v8")}
    meshes_by_id = {positive_int(node.attrib.get("ID")): node for node in assets.findall("Mesh")}
    bindings = {}
    for group in material_groups or []:
        material_id = positive_int(group.get("material_id"))
        material_name = str(group.get("material") or "")
        material = materials_by_id.get(material_id)
        if material is None or material.attrib.get("Name") != material_name:
            raise RuntimeError(
                f"Generated atlas material '{material_name}' (ID {material_id}) is missing from the target SPM."
            )
        material_mesh_ids = spm_material_mesh_ids(material)
        mesh_ids = [positive_int(value) for value in group.get("mesh_ids") or []]
        mesh_items = group.get("meshes") or []
        if len(mesh_ids) != len(mesh_items):
            raise RuntimeError(
                f"Generated atlas material '{material_name}' has {len(mesh_ids)} IDs for {len(mesh_items)} exported meshes."
            )
        for mesh_id, item in zip(mesh_ids, mesh_items):
            if mesh_id is None or mesh_id not in meshes_by_id:
                raise RuntimeError(f"Generated atlas mesh ID {mesh_id} is missing from the target SPM.")
            if mesh_id not in material_mesh_ids:
                raise RuntimeError(
                    f"Generated atlas mesh ID {mesh_id} is not owned by material '{material_name}'."
                )
            source_object = str(item.get("source_object") or "")
            match = re.search(r"(?:^|[^a-z0-9])leaf[_ -]?(\d+)", source_object, re.IGNORECASE)
            if not match:
                raise RuntimeError(
                    f"Exported mesh '{item.get('name') or source_object}' has no leaf_NN source ordinal."
                )
            ordinal = int(match.group(1))
            binding = {
                "leaf_ordinal": ordinal,
                "target_material_id": material_id,
                "target_material_name": material_name,
                "target_mesh_id": mesh_id,
                "source_object": source_object,
            }
            if ordinal in bindings and bindings[ordinal] != binding:
                raise RuntimeError(f"More than one generated atlas mesh claims leaf ordinal {ordinal}.")
            bindings[ordinal] = binding
    if not bindings:
        raise RuntimeError("No generated atlas mesh bindings were available for Generator connection.")
    return bindings


def connect_atlas_generators_in_spm(
    spm_path,
    source_material_names,
    material_groups,
    source_material_ids=None,
):
    """Connect source Leaf Mesh/Frond slots to generated atlas assets.

    The source material's CutoutMeshID/SupplementalCutoutMeshIDs order is the
    stable leaf ordinal. Exported Blender source objects named leaf_NN select
    the generated material/mesh pair for that ordinal.
    """
    spm_path = Path(spm_path)
    if not spm_path.exists():
        raise RuntimeError(f"Target SPM does not exist: {spm_path}")
    root = read_spm_xml(spm_path)
    assets = root.find("Assets")
    if assets is None:
        raise RuntimeError("Target SPM has no Assets node.")
    names, source_records = source_materials_by_name(
        assets,
        source_material_names,
        source_material_ids,
    )
    output_bindings = atlas_output_bindings(assets, material_groups)
    generated_pair_to_binding = {
        (item["target_material_id"], item["target_mesh_id"]): item
        for item in output_bindings.values()
    }

    staged = []
    already = []
    for pair in spm_generator_property_pairs(root, {"Leaf Mesh", "Frond"}):
        material_property = pair["material_property"]
        mesh_property = pair["mesh_property"]
        material_id = positive_int(material_property.findtext("Value"))
        mesh_id = integer_value(mesh_property.findtext("Value")) if mesh_property is not None else None
        if material_id in source_records:
            if mesh_property is None:
                raise RuntimeError(
                    f"Generator '{pair['generator_name']}' slot '{pair['slot_prefix']}' has Material but no Mesh property."
                )
            source = source_records[material_id]
            sentinel_policy = None
            if mesh_id == -10:
                # SpeedTree uses -10 as a non-specific mesh selection. A split
                # generated atlas can span several material groups, so there is
                # no single material whose cutout list can safely retain that
                # sentinel. Bind it deterministically to the first exported leaf.
                ordinal = 1
                sentinel_policy = "mesh_-10_to_first_generated_leaf"
            elif mesh_id not in source["mesh_ids"]:
                raise RuntimeError(
                    f"Generator '{pair['generator_name']}' mesh ID {mesh_id} is not in source material "
                    f"'{source['name']}' cutout mesh list {source['mesh_ids']}."
                )
            else:
                ordinal = source["mesh_ids"].index(mesh_id) + 1
            target = output_bindings.get(ordinal)
            if target is None:
                raise RuntimeError(
                    f"Generator '{pair['generator_name']}' needs leaf_{ordinal:02d}, but that atlas mesh was not exported."
                )
            staged.append((pair, source, mesh_id, target, sentinel_policy))
            continue
        target = generated_pair_to_binding.get((material_id, mesh_id))
        if target is not None:
            already.append((pair, target))

    if not staged and not already:
        raise RuntimeError(
            "No Leaf Mesh/Frond Generator slot references the requested source materials or this generated atlas."
        )

    bindings = []
    for pair, source, source_mesh_id, target, sentinel_policy in staged:
        child_text(pair["material_property"], "Value", target["target_material_id"])
        child_text(pair["mesh_property"], "Value", target["target_mesh_id"])
        bindings.append(
            {
                "state": "changed",
                "generator_index": pair["generator_index"],
                "generator_name": pair["generator_name"],
                "generator_type": pair["generator_type"],
                "slot_prefix": pair["slot_prefix"],
                "source_material_id": positive_int(source["material"].attrib.get("ID")),
                "source_material_name": source["name"],
                "source_mesh_id": source_mesh_id,
                "sentinel_policy": sentinel_policy,
                **target,
            }
        )
    for pair, target in already:
        bindings.append(
            {
                "state": "already_connected",
                "generator_index": pair["generator_index"],
                "generator_name": pair["generator_name"],
                "generator_type": pair["generator_type"],
                "slot_prefix": pair["slot_prefix"],
                "source_material_id": None,
                "source_material_name": None,
                "source_mesh_id": None,
                "sentinel_policy": None,
                **target,
            }
        )

    if staged:
        write_spm_xml(spm_path, root)
    validated_root = read_spm_xml(spm_path)
    validated_pairs = {
        (pair["generator_index"], pair["slot_prefix"]): pair
        for pair in spm_generator_property_pairs(validated_root, {"Leaf Mesh", "Frond"})
    }
    for binding in bindings:
        pair = validated_pairs.get((binding["generator_index"], binding["slot_prefix"]))
        if pair is None or pair["mesh_property"] is None:
            raise RuntimeError("Generator connection validation failed: slot pair disappeared after write.")
        material_id = positive_int(pair["material_property"].findtext("Value"))
        mesh_id = positive_int(pair["mesh_property"].findtext("Value"))
        if (material_id, mesh_id) != (binding["target_material_id"], binding["target_mesh_id"]):
            raise RuntimeError(
                f"Generator connection validation failed for '{binding['generator_name']}' "
                f"slot '{binding['slot_prefix']}'."
            )

    return {
        "requested": True,
        "complete": True,
        "source_material_names": names,
        "matched_generators": len({item["generator_index"] for item in bindings}),
        "changed_slot_pairs": len(staged),
        "already_connected_slot_pairs": len(already),
        "bindings": bindings,
    }


def read_json_file(path, fallback):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return fallback


def find_material_by_name(assets, material_name):
    if assets is None:
        return None
    for node in assets.findall("Material_v8"):
        if node.attrib.get("Name") == material_name:
            return node
    return None


def material_scope_matches(material, manifest):
    user_data = parse_atlas_leaf_spm_user_data(material.findtext("UserData"))
    return bool(user_data) and user_data.get("scope") == spm_export_scope(manifest)


def material_legacy_scope_matches(material, manifest, material_name):
    """Recognize an Atlas Leaf material authored before persistent UUID scopes."""
    user_data = parse_atlas_leaf_spm_user_data(material.findtext("UserData"))
    if not user_data or user_data.get("kind") != "material":
        return False
    existing_name = str(material.attrib.get("Name") or "")
    if str(user_data.get("scope") or "") != existing_name or existing_name != str(material_name):
        return False

    legacy_group = str(user_data.get("group") or "")
    current_group = str(manifest.get("material_collection") or "")
    return not legacy_group or not current_group or legacy_group == current_group


def material_untagged_legacy_meshes_match(
    material,
    manifest,
    material_name,
    spm_path,
    mesh_nodes_by_id,
    mesh_paths,
):
    """Recognize pre-ownership-tag exports by their exact external mesh paths."""
    if str(material.attrib.get("Name") or "") != str(material_name):
        return False
    if str(material.findtext("UserData") or "").strip():
        return False

    mesh_ids = spm_material_mesh_ids(material)
    if not mesh_ids or len(mesh_ids) != len(mesh_paths):
        return False

    existing_paths = []
    for mesh_id in mesh_ids:
        mesh_node = mesh_nodes_by_id.get(str(mesh_id))
        if mesh_node is None or str(mesh_node.findtext("UserData") or "").strip():
            return False
        mesh_path = spm_mesh_filename_path(spm_path, mesh_node)
        if mesh_path is None:
            return False
        existing_paths.append(normalized_mesh_lookup_key(mesh_path))

    expected_paths = [
        normalized_mesh_lookup_key(Path(mesh_path).resolve())
        for mesh_path in mesh_paths
    ]
    return sorted(existing_paths) == sorted(expected_paths)


def find_scope_group_material(assets, manifest):
    if assets is None:
        return None
    group = str(manifest.get("material_collection") or "")
    if not group:
        return None
    for node in assets.findall("Material_v8"):
        user_data = parse_atlas_leaf_spm_user_data(node.findtext("UserData"))
        if not user_data or user_data.get("scope") != spm_export_scope(manifest):
            continue
        if str(user_data.get("group") or "") == group:
            return node
    return None


def manifest_material_names(manifest):
    names = set()
    if not isinstance(manifest, dict):
        return names
    for key in ("material", "material_name"):
        value = manifest.get(key)
        if value:
            names.add(str(value))
    for group_key in ("material_groups", "speedtree_material_groups"):
        for group in manifest.get(group_key) or []:
            value = group.get("material") if isinstance(group, dict) else None
            if value:
                names.add(str(value))
    return names


def manifest_mesh_asset_paths(manifest):
    paths = set()
    if not isinstance(manifest, dict):
        return paths

    def collect_meshes(meshes):
        for item in meshes or []:
            if not isinstance(item, dict):
                continue
            for key in ("asset", "fbx", "xml"):
                value = item.get(key)
                if value:
                    paths.add(Path(value).resolve())

    collect_meshes(manifest.get("meshes"))
    for group in manifest.get("material_groups") or []:
        if isinstance(group, dict):
            collect_meshes(group.get("meshes"))
    return paths


def path_is_relative_to(path, parent):
    try:
        Path(path).resolve().relative_to(Path(parent).resolve())
        return True
    except ValueError:
        return False


def spm_mesh_filename_path(spm_path, mesh_node):
    filename = mesh_node.findtext("Filename") or ""
    if not filename:
        return None
    filename_path = Path(filename.replace("\\", "/"))
    if filename_path.is_absolute():
        return filename_path.resolve()
    return (Path(spm_path).resolve().parent / filename_path).resolve()


def normalized_mesh_lookup_key(value):
    return str(value).replace("\\", "/").lower()


def mesh_path_lookup_keys(spm_path, mesh_path):
    path = Path(mesh_path)
    keys = {normalized_mesh_lookup_key(path.name)}
    keys.add(normalized_mesh_lookup_key(relative_spm_path(spm_path, path)))
    try:
        keys.add(normalized_mesh_lookup_key(path.resolve()))
    except OSError:
        keys.add(normalized_mesh_lookup_key(path))
    return keys


def add_mesh_lookup(mesh_ids_by_key, mesh_key_counts, key, mesh_id):
    if not key:
        return
    mesh_key_counts[key] = mesh_key_counts.get(key, 0) + 1
    mesh_ids_by_key.setdefault(key, mesh_id)


def build_spm_mesh_lookup(spm_path, mesh_nodes_by_id):
    mesh_ids_by_key = {}
    mesh_key_counts = {}
    for mesh_id_text, node in mesh_nodes_by_id.items():
        try:
            mesh_id = int(mesh_id_text)
        except (TypeError, ValueError):
            continue
        filename = node.findtext("Filename") or ""
        if filename:
            add_mesh_lookup(mesh_ids_by_key, mesh_key_counts, normalized_mesh_lookup_key(filename), mesh_id)
            add_mesh_lookup(mesh_ids_by_key, mesh_key_counts, normalized_mesh_lookup_key(Path(filename).name), mesh_id)
            mesh_path = spm_mesh_filename_path(spm_path, node)
            if mesh_path is not None:
                add_mesh_lookup(mesh_ids_by_key, mesh_key_counts, normalized_mesh_lookup_key(mesh_path), mesh_id)
        node_name = node.attrib.get("Name")
        if node_name:
            add_mesh_lookup(mesh_ids_by_key, mesh_key_counts, normalized_mesh_lookup_key(f"{node_name}.fbx"), mesh_id)
    return mesh_ids_by_key, mesh_key_counts


def existing_spm_mesh_id_for_path(spm_path, mesh_path, mesh_ids_by_key, mesh_key_counts):
    keys = list(mesh_path_lookup_keys(spm_path, mesh_path))
    exact_keys = [key for key in keys if "/" in key or ":" in key]
    fallback_keys = [key for key in keys if key not in exact_keys]
    for key in exact_keys + fallback_keys:
        if mesh_key_counts.get(key) == 1:
            mesh_id = mesh_ids_by_key.get(key)
            if mesh_id is not None:
                return mesh_id
    return None


def material_is_atlas_leaf_owned(material, manifest, previous_material_names, mesh_nodes_by_id, spm_path):
    user_data = parse_atlas_leaf_spm_user_data(material.findtext("UserData"))
    if user_data and user_data.get("scope") == spm_export_scope(manifest):
        return True

    export_mesh_dir = Path(spm_path).resolve().parent / "meshes"
    mesh_ids = spm_material_mesh_ids(material)
    if not mesh_ids:
        return False
    for mesh_id in mesh_ids:
        mesh_node = mesh_nodes_by_id.get(str(mesh_id))
        mesh_path = spm_mesh_filename_path(spm_path, mesh_node) if mesh_node is not None else None
        if mesh_path is None or not path_is_relative_to(mesh_path, export_mesh_dir):
            return False
    return material.attrib.get("Name") in previous_material_names


def remove_stale_mesh_files(spm_path, removed_mesh_nodes, previous_paths, current_paths):
    export_mesh_dir = Path(spm_path).resolve().parent / "meshes"
    candidates = set()
    for node in removed_mesh_nodes:
        mesh_path = spm_mesh_filename_path(spm_path, node)
        if mesh_path is not None:
            candidates.add(mesh_path)
    candidates.update(path for path in previous_paths if path_is_relative_to(path, export_mesh_dir))

    removed = []
    for path in sorted(candidates, key=lambda item: str(item).lower()):
        if path in current_paths or not path_is_relative_to(path, export_mesh_dir):
            continue
        try:
            if path.exists() and path.is_file():
                path.unlink()
                removed.append(str(path))
        except OSError:
            continue
    return removed


def cleanup_stale_spm_assets(spm_path, manifest, active_material_names, previous_manifest=None):
    previous_manifest = previous_manifest or {}
    previous_manifest_in_scope = manifests_share_export_scope(manifest, previous_manifest)
    previous_material_names = manifest_material_names(previous_manifest) if previous_manifest_in_scope else set()
    previous_paths = manifest_mesh_asset_paths(previous_manifest) if previous_manifest_in_scope else set()
    current_paths = manifest_mesh_asset_paths(manifest)

    root = read_spm_xml(spm_path)
    assets = root.find("Assets")
    if assets is None:
        return {"removed_materials": [], "removed_mesh_ids": [], "removed_mesh_files": []}

    mesh_nodes_by_id = {node.attrib.get("ID"): node for node in assets.findall("Mesh")}
    generator_referenced_material_ids = spm_generator_referenced_material_ids(root)
    generator_referenced_mesh_ids = spm_generator_referenced_mesh_ids(root)
    removed_materials = []
    removed_material_mesh_ids = set()
    for material in list(assets.findall("Material_v8")):
        material_name = material.attrib.get("Name", "")
        if material_name in active_material_names:
            continue
        material_id = positive_int(material.attrib.get("ID"))
        if material_id in generator_referenced_material_ids:
            continue
        if not material_is_atlas_leaf_owned(material, manifest, previous_material_names, mesh_nodes_by_id, spm_path):
            continue
        removed_materials.append(material_name)
        removed_material_mesh_ids.update(spm_material_mesh_ids(material))
        assets.remove(material)

    remaining_mesh_ids = set()
    for material in assets.findall("Material_v8"):
        remaining_mesh_ids.update(spm_material_mesh_ids(material))
    # Material and Mesh references are independent SpeedTree properties. A
    # Generator can keep using a mesh even when its former managed material is
    # removed or renamed, so protect every directly referenced Mesh ID too.
    remaining_mesh_ids.update(generator_referenced_mesh_ids)

    removed_mesh_nodes = []
    removed_mesh_ids = []
    for mesh in list(assets.findall("Mesh")):
        mesh_id_text = mesh.attrib.get("ID")
        try:
            mesh_id = int(mesh_id_text or "0")
        except ValueError:
            continue
        if mesh_id in remaining_mesh_ids:
            continue
        user_data = parse_atlas_leaf_spm_user_data(mesh.findtext("UserData"))
        mesh_path = spm_mesh_filename_path(spm_path, mesh)
        owned_by_marker = user_data and user_data.get("scope") == spm_export_scope(manifest)
        owned_by_previous_manifest = mesh_path in previous_paths if mesh_path is not None else False
        owned_by_removed_material = mesh_id in removed_material_mesh_ids
        if owned_by_marker or owned_by_previous_manifest or owned_by_removed_material:
            removed_mesh_nodes.append(mesh)
            removed_mesh_ids.append(mesh_id)
            assets.remove(mesh)

    removed_mesh_files = remove_stale_mesh_files(spm_path, removed_mesh_nodes, previous_paths, current_paths)
    if removed_materials or removed_mesh_ids:
        write_spm_xml(spm_path, root)
    return {
        "removed_materials": removed_materials,
        "removed_mesh_ids": removed_mesh_ids,
        "removed_mesh_files": removed_mesh_files,
    }


def make_spm_mesh(mesh_template, mesh_id, fbx_path, spm_path, manifest=None):
    mesh = copy.deepcopy(mesh_template)
    mesh.attrib["ID"] = str(mesh_id)
    mesh.attrib["Name"] = Path(fbx_path).stem
    child_text(mesh, "Filename", relative_spm_path(spm_path, fbx_path))
    child_text(mesh, "FixWinding", "false")
    child_text(mesh, "FlipNormals", "false")
    child_text(mesh, "Embedded", "false")
    child_text(mesh, "Orient", "6")
    child_text(mesh, "PivotStyle", "0")
    child_text(mesh, "Scale", "1")
    for child in list(mesh):
        if child.tag.startswith("Lod_") or child.tag == "EmbeddedData_v7" or child.tag == "Cutout":
            mesh.remove(child)
    if manifest is not None:
        tag_spm_asset(mesh, manifest, "mesh")
    return mesh


def create_speedtree_spm(spm_path, manifest, material_name):
    if not SPEEDTREE_101_BLANK_SPM.exists():
        raise RuntimeError(f"SpeedTree 10.1 Blank.spm not found: {SPEEDTREE_101_BLANK_SPM}")
    if not SPEEDTREE_101_MATERIAL_SAMPLE.exists():
        raise RuntimeError(f"SpeedTree 10.1 material sample not found: {SPEEDTREE_101_MATERIAL_SAMPLE}")
    if not SPEEDTREE_101_EXTERNAL_MESH_SAMPLE.exists():
        raise RuntimeError(f"SpeedTree 10.1 mesh sample not found: {SPEEDTREE_101_EXTERNAL_MESH_SAMPLE}")

    spm_path = Path(spm_path)
    spm_path.parent.mkdir(parents=True, exist_ok=True)
    root = read_spm_xml(SPEEDTREE_101_BLANK_SPM)
    root.attrib["Title"] = " Elm01 Atlas Leaf Mesh Assets "
    root.attrib["VersionString"] = "10.1.0 "

    assets = root.find("Assets")
    if assets is None:
        assets = ET.SubElement(root, "Assets")

    for node in list(assets):
        if node.tag in {"Material_v8", "Mesh"}:
            assets.remove(node)

    mesh_paths = [Path(item.get("asset") or item["fbx"]) for item in manifest["meshes"]]
    mesh_ids = list(range(1, len(mesh_paths) + 1))
    material = make_spm_material(spm_path, manifest["textures"], mesh_ids, material_name, manifest)
    mesh_template = first_external_mesh_template()
    insert_index = 0
    assets.insert(insert_index, material)
    insert_index += 1
    for mesh_id, mesh_path in zip(mesh_ids, mesh_paths):
        assets.insert(insert_index, make_spm_mesh(mesh_template, mesh_id, mesh_path, spm_path, manifest))
        insert_index += 1

    write_spm_xml(spm_path, root)
    parsed = read_spm_xml(spm_path)
    parsed_assets = parsed.find("Assets")
    material_count = len(parsed_assets.findall("Material_v8")) if parsed_assets is not None else 0
    mesh_count = len(parsed_assets.findall("Mesh")) if parsed_assets is not None else 0
    if material_count != 1 or mesh_count != len(mesh_paths):
        raise RuntimeError("Generated SPM validation failed.")
    return spm_path, "created", 1, mesh_ids


def max_asset_id(assets, tag):
    maximum = 0
    if assets is None:
        return maximum
    for node in assets.findall(tag):
        try:
            maximum = max(maximum, int(node.attrib.get("ID", "0")))
        except ValueError:
            continue
    return maximum


def upsert_speedtree_assets_in_spm(spm_path, manifest, material_name, allow_create=False):
    spm_path = Path(spm_path)
    if not spm_path.exists():
        if not allow_create:
            raise RuntimeError(
                f"Target SPM does not exist: {spm_path}. Enable explicit create to build a blank target."
            )
        return create_speedtree_spm(spm_path, manifest, material_name)

    if not SPEEDTREE_101_MATERIAL_SAMPLE.exists():
        raise RuntimeError(f"SpeedTree 10.1 material sample not found: {SPEEDTREE_101_MATERIAL_SAMPLE}")
    if not SPEEDTREE_101_EXTERNAL_MESH_SAMPLE.exists():
        raise RuntimeError(f"SpeedTree 10.1 mesh sample not found: {SPEEDTREE_101_EXTERNAL_MESH_SAMPLE}")

    root = read_spm_xml(spm_path)
    assets = root.find("Assets")
    if assets is None:
        assets = ET.SubElement(root, "Assets")

    mesh_paths = [Path(item.get("asset") or item["fbx"]) for item in manifest["meshes"]]
    mesh_template = first_external_mesh_template()
    mesh_nodes_by_id = {node.attrib.get("ID"): node for node in assets.findall("Mesh")}
    mesh_ids_by_key, mesh_key_counts = build_spm_mesh_lookup(spm_path, mesh_nodes_by_id)

    named_material = find_material_by_name(assets, material_name)
    scoped_material = find_scope_group_material(assets, manifest)
    untagged_legacy_match = (
        named_material is not None
        and material_untagged_legacy_meshes_match(
            named_material,
            manifest,
            material_name,
            spm_path,
            mesh_nodes_by_id,
            mesh_paths,
        )
    )
    if (
        named_material is not None
        and not material_scope_matches(named_material, manifest)
        and not material_legacy_scope_matches(named_material, manifest, material_name)
        and not untagged_legacy_match
    ):
        raise RuntimeError(
            f"Material name conflict in {spm_path.name}: '{material_name}' belongs to another atlas/source. "
            "Choose a unique atlas asset name instead of overwriting it."
        )
    if scoped_material is not None and named_material is not None and scoped_material is not named_material:
        raise RuntimeError(
            f"Atlas export scope already owns a different material while '{material_name}' is also present."
        )
    material = scoped_material or named_material
    action = "updated"
    old_mesh_ids = []
    if material is None:
        # The material may have been renamed (blend file or collection rename).
        # Only reclaim materials this export scope actually owns — a bare name
        # match could hijack another atlas's material in a shared SPM.
        action = "injected"
        material_id = max_asset_id(assets, "Material_v8") + 1
        first_mesh_id = max_asset_id(assets, "Mesh") + 1
        mesh_ids = list(range(first_mesh_id, first_mesh_id + len(mesh_paths)))
        material = make_spm_material(spm_path, manifest["textures"], mesh_ids, material_name, manifest)
        material.attrib["ID"] = str(material_id)
        assets.append(material)
    elif material.attrib.get("Name") != material_name:
        action = "renamed"
        material.attrib["Name"] = material_name

    if action in {"renamed", "updated"}:
        material_id = int(material.attrib.get("ID", max_asset_id(assets, "Material_v8") + 1))
        old_mesh_ids = spm_material_mesh_ids(material)
        old_mesh_id_set = set(old_mesh_ids)
        mesh_ids = []
        used_mesh_ids = set()
        for mesh_path in mesh_paths:
            existing_id = existing_spm_mesh_id_for_path(spm_path, mesh_path, mesh_ids_by_key, mesh_key_counts)
            if existing_id in old_mesh_id_set and existing_id not in used_mesh_ids:
                mesh_ids.append(existing_id)
                used_mesh_ids.add(existing_id)
            else:
                mesh_ids.append(None)
        reusable_old_ids = [mesh_id for mesh_id in old_mesh_ids if mesh_id not in used_mesh_ids]
        next_mesh_id = max_asset_id(assets, "Mesh") + 1
        for index, mesh_id in enumerate(mesh_ids):
            if mesh_id is not None:
                continue
            if reusable_old_ids:
                mesh_ids[index] = reusable_old_ids.pop(0)
            else:
                mesh_ids[index] = next_mesh_id
                next_mesh_id += 1
        update_spm_material(material, spm_path, manifest["textures"], mesh_ids)
        tag_spm_asset(material, manifest, "material")

    for mesh_id, mesh_path in zip(mesh_ids, mesh_paths):
        mesh_node = mesh_nodes_by_id.get(str(mesh_id))
        new_mesh = make_spm_mesh(mesh_template, mesh_id, mesh_path, spm_path, manifest)
        if mesh_node is None:
            assets.append(new_mesh)
        else:
            insert_at = list(assets).index(mesh_node)
            assets.remove(mesh_node)
            assets.insert(insert_at, new_mesh)

    unused_old_ids = set(old_mesh_ids) - set(mesh_ids)
    generator_referenced_mesh_ids = spm_generator_referenced_mesh_ids(root)
    removable_unused_old_ids = unused_old_ids - generator_referenced_mesh_ids
    if removable_unused_old_ids:
        for node in list(assets.findall("Mesh")):
            try:
                mesh_id = int(node.attrib.get("ID", "0"))
            except ValueError:
                continue
            if mesh_id in removable_unused_old_ids:
                assets.remove(node)

    write_spm_xml(spm_path, root)

    parsed = read_spm_xml(spm_path)
    parsed_assets = parsed.find("Assets")
    parsed_material = None
    for node in parsed_assets.findall("Material_v8"):
        if node.attrib.get("ID") == str(material_id):
            parsed_material = node
            break
    if parsed_material is None:
        raise RuntimeError("SpeedTree SPM validation failed: material was not written.")
    parsed_mesh_ids = {node.attrib.get("ID") for node in parsed_assets.findall("Mesh")}
    parsed_material_mesh_ids = spm_material_mesh_ids(parsed_material)
    if parsed_material_mesh_ids != mesh_ids:
        raise RuntimeError(
            f"SpeedTree SPM validation failed: material mesh IDs are {parsed_material_mesh_ids}, expected {mesh_ids}."
        )
    missing_mesh_ids = [str(mesh_id) for mesh_id in mesh_ids if str(mesh_id) not in parsed_mesh_ids]
    if missing_mesh_ids:
        raise RuntimeError(f"SpeedTree SPM validation failed: missing mesh IDs {missing_mesh_ids}")
    stale_mesh_ids = [str(mesh_id) for mesh_id in removable_unused_old_ids if str(mesh_id) in parsed_mesh_ids]
    if stale_mesh_ids:
        raise RuntimeError(f"SpeedTree SPM validation failed: stale deleted mesh IDs remain {stale_mesh_ids}")
    return spm_path, action, material_id, mesh_ids


def cleanup_stale_mesh_exports(export_dir, exported_meshes):
    # Keep stale FBX files on disk. SpeedTree .spm files can keep external Mesh
    # references across several atlas/material update passes, and deleting an old
    # FBX from a shared meshes/ folder can break another material even when the
    # current manifest no longer lists it.
    return []


def material_suffix_from_collection_name(collection_name):
    text = collection_name.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text or "group"


def sanitize_filename_component(text, fallback="asset"):
    cleaned = re.sub(r'[\\/:*?"<>|]+', "_", str(text))
    cleaned = re.sub(r"_+", "_", cleaned).strip(" ._")
    return cleaned or fallback


def canonical_new_atlas_asset_name(value):
    name = sanitize_filename_component(value, "AtlasLeaf")
    if re.match(r"(?i)^M_cluster_", name):
        name = "M_leaf_" + name[len("M_cluster_") :]
    return name


def blender_material_base_name(root_collection, atlas_asset_name=None):
    if atlas_asset_name:
        # Canonicalization is intentionally limited to an explicit new output
        # request. Opening a legacy M_cluster blend does not silently rename its
        # already-authored SpeedTree material.
        return canonical_new_atlas_asset_name(atlas_asset_name)
    if bpy.data.filepath:
        return Path(bpy.data.filepath).stem
    return sanitize_filename_component(root_collection.name.strip(), "AtlasLeaf")


def material_name_from_collection(root_collection, collection=None, atlas_asset_name=None):
    base_name = blender_material_base_name(root_collection, atlas_asset_name)
    if collection is None or collection == root_collection:
        return base_name
    suffix = material_suffix_from_collection_name(collection.name)
    return f"{base_name}_{suffix}"


def grouped_source_objects(root_collection, atlas_asset_name=None):
    def is_export_source(obj):
        return obj.type == "MESH" and not obj.name.lower().startswith("codex_")

    direct_objects = [obj for obj in root_collection.objects if is_export_source(obj)]
    child_groups = []

    def collect_meshes(collection, output):
        for obj in collection.objects:
            if is_export_source(obj):
                output.append(obj)
        for child in collection.children:
            collect_meshes(child, output)

    for child in root_collection.children:
        objects = []
        collect_meshes(child, objects)
        if objects:
            child_groups.append(
                {
                    "collection": child.name,
                    "material": material_name_from_collection(root_collection, child, atlas_asset_name),
                    "objects": objects,
                }
            )

    if not child_groups:
        return [
            {
                "collection": root_collection.name,
                "material": material_name_from_collection(root_collection, atlas_asset_name=atlas_asset_name),
                "objects": direct_objects,
            }
        ]

    groups = child_groups
    if direct_objects:
        groups.append(
            {
                "collection": root_collection.name,
                "material": material_name_from_collection(root_collection, atlas_asset_name=atlas_asset_name),
                "objects": direct_objects,
            }
        )
    return groups


def speedtree_mesh_sort_key(obj):
    match = re.search(r"leaf_(\d+).*front_(\d+)", obj.name, re.IGNORECASE)
    if match:
        return (int(match.group(1)), int(match.group(2)), obj.name.lower())
    match = re.search(r"(\d+)", obj.name)
    if match:
        return (int(match.group(1)), int(match.group(1)), obj.name.lower())
    return (10_000_000, 10_000_000, obj.name.lower())


def speedtree_mesh_export_name(source, used_names, group_material=None):
    match = re.search(r"leaf_(\d+)", source.name, re.IGNORECASE)
    prefix = f"{int(match.group(1)):02d}" if match else f"{len(used_names) + 1:02d}"
    group_prefix = ""
    if group_material:
        group_prefix = material_suffix_from_collection_name(group_material) + "__"
    source_name = sanitize_filename_component(source.name, "mesh")
    candidate = f"{group_prefix}{prefix}_{source_name}.fbx"
    suffix = 2
    while candidate.lower() in used_names:
        candidate = f"{group_prefix}{prefix}_{source_name}_{suffix}.fbx"
        suffix += 1
    used_names.add(candidate.lower())
    return candidate


def _matrix_is_identity(matrix, tolerance=1.0e-6):
    identity = Matrix.Identity(4)
    return all(
        abs(matrix[row][col] - identity[row][col]) <= tolerance
        for row in range(4)
        for col in range(4)
    )


def apply_source_mesh_transforms(source_groups):
    """Bake each source mesh object's world transform into its mesh data so the
    exported pivot sits at the world origin.

    Only MESH objects are applied. Anchor empties and anchor containers are left
    untouched, and direct children of an applied mesh keep their world placement
    so anchor positions/rotations survive the apply.
    """
    identity = Matrix.Identity(4)
    applied = []
    seen = set()
    for group in source_groups:
        for obj in group["objects"]:
            if obj.name in seen or obj.type != "MESH":
                continue
            seen.add(obj.name)
            world = obj.matrix_world.copy()
            if _matrix_is_identity(world):
                continue
            child_worlds = [(child, child.matrix_world.copy()) for child in obj.children]
            if obj.data.users > 1:
                obj.data = obj.data.copy()
            obj.data.transform(world)
            obj.data.update()
            obj.matrix_world = identity
            if child_worlds:
                bpy.context.view_layer.update()
                for child, child_world in child_worlds:
                    child.matrix_world = child_world
            applied.append(obj.name)
    if applied:
        bpy.context.view_layer.update()
    return applied


def export_speedtree_assets(props, export_dir, atlas_asset_name=None):
    collection = bpy.data.collections.get(props.collection_name)
    if not collection:
        raise RuntimeError(f"Collection not found: {props.collection_name}")
    texture_exports = {
        key: str(path.resolve())
        for key, path in atlas_texture_paths(bpy.path.abspath(props.albedo_path)).items()
        if path.exists()
    }
    texture_signature = texture_path_signature(texture_exports)
    export_scope_id = resolve_export_scope_id(collection, export_dir, texture_signature)

    source_groups = grouped_source_objects(collection, atlas_asset_name)
    if not any(group["objects"] for group in source_groups):
        raise RuntimeError(f"No mesh objects in collection: {props.collection_name}")

    # SpeedTree misplaces external meshes whose FBX pivot is not at the origin,
    # so bake every source mesh's transform before export. Anchor empties keep
    # their world placement (their values must not be zeroed by the apply).
    applied_transform_objects = apply_source_mesh_transforms(source_groups)

    if not hasattr(bpy.ops.export_scene, "fbx"):
        try:
            bpy.ops.preferences.addon_enable(module="io_scene_fbx")
        except Exception as exc:
            raise RuntimeError("Blender FBX exporter is not available.") from exc
    if not hasattr(bpy.ops.export_scene, "fbx"):
        raise RuntimeError("Blender FBX exporter is not available.")

    export_dir = Path(export_dir)
    mesh_dir = export_dir / "meshes"
    mesh_dir.mkdir(parents=True, exist_ok=True)

    materials = {
        group["material"]: make_speedtree_material(group["material"], bpy.path.abspath(props.albedo_path))
        for group in source_groups
        if group["objects"]
    }
    mesh_geometry_scale = max(float(props.speedtree_mesh_scale), 0.000001)

    temp_collection_name = "_AtlasLeaf_SpeedTree_Export_Temp"
    temp_collection = bpy.data.collections.get(temp_collection_name)
    if temp_collection:
        for obj in list(temp_collection.objects):
            bpy.data.objects.remove(obj, do_unlink=True)
    else:
        temp_collection = bpy.data.collections.new(temp_collection_name)
        bpy.context.scene.collection.children.link(temp_collection)

    previous_selection = list(bpy.context.selected_objects)
    previous_active = bpy.context.view_layer.objects.active
    depsgraph = bpy.context.evaluated_depsgraph_get()
    exported_meshes = []
    material_groups = []
    used_mesh_filenames = set()
    anchor_export_mode = getattr(props, "speedtree_anchor_export_mode", "OFF")
    try:
        for group in source_groups:
            group_meshes = []
            material = materials.get(group["material"])
            if material is None:
                continue
            for source in sorted(group["objects"], key=speedtree_mesh_sort_key):
                anchor_records = []
                if anchor_export_mode != "OFF":
                    anchor_records = collect_source_anchors(source, props, mesh_geometry_scale)
                evaluated = source.evaluated_get(depsgraph)
                mesh = bpy.data.meshes.new_from_object(evaluated, depsgraph=depsgraph)
                mesh.materials.clear()
                mesh.materials.append(material)
                for poly in mesh.polygons:
                    poly.material_index = 0
                if mesh_geometry_scale != 1.0:
                    for vertex in mesh.vertices:
                        vertex.co *= mesh_geometry_scale
                    mesh.update()
                export_name = speedtree_mesh_export_name(
                    source,
                    used_mesh_filenames,
                    group["material"],
                )
                export_stem = Path(export_name).stem
                mesh.name = export_stem
                temp_obj = bpy.data.objects.new(export_stem, mesh)
                temp_obj.matrix_world = source.matrix_world.copy()
                temp_collection.objects.link(temp_obj)
                temp_anchor_objects = []
                if anchor_export_mode == "FBX_EMPTY":
                    for index, anchor in enumerate(anchor_records):
                        temp_anchor = bpy.data.objects.new(anchor["name"] or f"anchor_{index + 1:02d}", None)
                        temp_anchor.empty_display_type = "SINGLE_ARROW"
                        temp_anchor.empty_display_size = max(float(anchor["scale"]) * 0.1, 0.01)
                        temp_anchor["atlas_leaf_speedtree_anchor"] = True
                        temp_collection.objects.link(temp_anchor)
                        temp_anchor.matrix_world = temp_obj.matrix_world @ anchor["local_matrix"]
                        temp_anchor_objects.append(temp_anchor)

                for obj in bpy.context.selected_objects:
                    obj.select_set(False)
                temp_obj.select_set(True)
                for temp_anchor in temp_anchor_objects:
                    temp_anchor.select_set(True)
                bpy.context.view_layer.objects.active = temp_obj

                fbx_path = mesh_dir / export_name
                bpy.ops.export_scene.fbx(
                    filepath=str(fbx_path),
                    use_selection=True,
                    object_types={"MESH", "EMPTY"} if anchor_export_mode == "FBX_EMPTY" else {"MESH"},
                    apply_unit_scale=True,
                    bake_space_transform=False,
                    add_leaf_bones=False,
                    path_mode="RELATIVE",
                    embed_textures=False,
                )
                xml_path = None
                asset_path = fbx_path
                if anchor_export_mode == "XML" and anchor_records:
                    xml_path = mesh_dir / f"{export_stem}.xml"
                    write_speedtree_xml_mesh(xml_path, mesh, material.name, anchor_records)
                    asset_path = xml_path
                item = {
                    "name": export_stem,
                    "fbx": str(fbx_path),
                    "xml": str(xml_path) if xml_path else None,
                    "asset": str(asset_path),
                    "anchor_count": len(anchor_records),
                    "anchor_names": [anchor["name"] for anchor in anchor_records],
                    "source_object": source.name,
                    "source_collection": group["collection"],
                    "material": material.name,
                }
                exported_meshes.append(item)
                group_meshes.append(item)
                for temp_anchor in temp_anchor_objects:
                    bpy.data.objects.remove(temp_anchor, do_unlink=True)
                bpy.data.objects.remove(temp_obj, do_unlink=True)
                bpy.data.meshes.remove(mesh, do_unlink=True)
            if group_meshes:
                material_groups.append(
                    {
                        "collection": group["collection"],
                        "material": group["material"],
                        "mesh_count": len(group_meshes),
                        "meshes": group_meshes,
                    }
                )
    finally:
        for obj in bpy.context.selected_objects:
            obj.select_set(False)
        for obj in previous_selection:
            if obj.name in bpy.data.objects:
                obj.select_set(True)
        if previous_active and previous_active.name in bpy.data.objects:
            bpy.context.view_layer.objects.active = previous_active
        if temp_collection and not temp_collection.objects:
            bpy.data.collections.remove(temp_collection)

    removed_stale_mesh_exports = cleanup_stale_mesh_exports(export_dir, exported_meshes)

    manifest = {
        "source_collection": props.collection_name,
        "export_scope_id": export_scope_id,
        "blend_file": bpy.data.filepath,
        "texture_signature": texture_signature,
        "requested_atlas_asset_name": str(atlas_asset_name or ""),
        "atlas_asset_name": blender_material_base_name(collection, atlas_asset_name),
        "speedtree_version_target": "10.1.0",
        "material": material_groups[0]["material"] if len(material_groups) == 1 else None,
        "material_groups": material_groups,
        "single_material_per_mesh": True,
        "mesh_geometry_scale": mesh_geometry_scale,
        "applied_transform_objects": applied_transform_objects,
        "anchor_export_mode": anchor_export_mode,
        "anchor_count": sum(item.get("anchor_count", 0) for item in exported_meshes),
        "mesh_count": len(exported_meshes),
        "meshes": exported_meshes,
        "removed_stale_mesh_exports": removed_stale_mesh_exports,
        "textures": texture_exports,
        "notes": [
            "Use each mesh item's asset path as the SpeedTree mesh asset source.",
            "Use one atlas material for all leaf mesh variants.",
            "The SPM material mesh list is synchronized to the current Blender collection when rebuilt.",
            "Texture maps reference the original source files and are not copied into the SPM folder.",
            "The original roughness map is connected to the SpeedTree gloss slot when present.",
            "SpeedTree XML anchor assets store child empties as LeafReferences.",
            "Source mesh transforms are applied on build so FBX pivots sit at the origin; anchor empties keep their transforms.",
        ],
    }
    manifest_path = export_dir / "speedtree_import_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    readme_path = write_speedtree_readme(export_dir, manifest)
    return manifest_path, readme_path, exported_meshes


def normalized_target_key(path):
    try:
        value = str(Path(path).resolve())
    except OSError:
        value = str(path)
    return value.replace("\\", "/").lower()


def speedtree_source_material_mapping(props):
    raw = str(getattr(props, "speedtree_source_materials_json", "") or "").strip()
    if not raw:
        return {}
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Source material mapping JSON is invalid: {exc}") from exc
    if not isinstance(payload, dict):
        raise RuntimeError("Source material mapping JSON must be an object keyed by target SPM path.")
    mapping = {}
    for target, value in payload.items():
        if isinstance(value, dict):
            names = value.get("source_material_names") or value.get("materials") or []
            ids = value.get("source_material_ids")
        else:
            names = value
            ids = None
        if isinstance(names, str):
            names = [names]
        if not isinstance(names, list):
            raise RuntimeError(f"Source materials for '{target}' must be a list.")
        mapping[normalized_target_key(target)] = {
            "source_material_names": [str(name) for name in names if str(name).strip()],
            "source_material_ids": ids,
        }
    return mapping


def _export_or_update_speedtree_spm_path_impl(
    props,
    target_spm,
    *,
    atlas_asset_name=None,
    source_material_names=None,
    source_material_ids=None,
    allow_create=False,
):
    target_spm = Path(target_spm)
    if not target_spm.name:
        raise RuntimeError("Target SPM is not set.")
    if target_spm.suffix.lower() != ".spm":
        raise RuntimeError("Target SPM must end with .spm")
    if not target_spm.exists() and not allow_create:
        raise RuntimeError(
            f"Target SPM does not exist: {target_spm}. Enable explicit create to build a blank target."
        )

    if atlas_asset_name is None:
        atlas_asset_name = str(getattr(props, "speedtree_atlas_asset_name", "") or "").strip() or None

    previous_global_manifest_path = target_spm.parent / "speedtree_import_manifest.json"
    previous_global_manifest = read_json_file(previous_global_manifest_path, {})
    previous_target_manifest = read_json_file(target_manifest_path(target_spm), {})
    manifest_path, readme_path, exported_meshes = export_speedtree_assets(
        props,
        target_spm.parent,
        atlas_asset_name,
    )
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    fallback_manifest = previous_target_manifest or previous_global_manifest
    previous_manifest = previous_scope_manifest(
        target_spm.parent,
        manifest,
        fallback_manifest,
        target_spm,
    )
    material_groups = manifest.get("material_groups") or [
        {
            "collection": manifest.get("source_collection", props.collection_name),
            "material": manifest.get("source_collection", props.collection_name),
            "meshes": manifest.get("meshes", []),
        }
    ]

    group_results = []
    for group in material_groups:
        group_manifest = dict(manifest)
        group_manifest["meshes"] = group.get("meshes", [])
        group_manifest["material_collection"] = group.get("collection")
        if not group_manifest["meshes"]:
            continue
        material_name = group.get("material") or group.get("collection") or manifest.get("source_collection", props.collection_name)
        spm_path, action, material_id, mesh_ids = upsert_speedtree_assets_in_spm(
            target_spm,
            group_manifest,
            material_name,
            allow_create=allow_create,
        )
        group["material_id"] = material_id
        group["mesh_ids"] = mesh_ids
        group_results.append(
            {
                "collection": group.get("collection"),
                "material": material_name,
                "material_id": material_id,
                "mesh_ids": mesh_ids,
                "action": action,
            }
        )

    if not group_results:
        raise RuntimeError("No SpeedTree material groups contained meshes.")

    if source_material_names:
        generator_connection = connect_atlas_generators_in_spm(
            target_spm,
            source_material_names,
            material_groups,
            source_material_ids,
        )
    else:
        generator_connection = {
            "requested": False,
            "complete": False,
            "source_material_names": [],
            "matched_generators": 0,
            "changed_slot_pairs": 0,
            "already_connected_slot_pairs": 0,
            "bindings": [],
        }

    cleanup = cleanup_stale_spm_assets(
        target_spm,
        manifest,
        {group["material"] for group in group_results},
        previous_manifest,
    )
    action = ",".join(sorted({group["action"] for group in group_results}))
    if cleanup["removed_materials"] or cleanup["removed_mesh_ids"]:
        action = f"{action},cleaned"
    material_id = group_results[0]["material_id"]
    mesh_ids = [mesh_id for group in group_results for mesh_id in group["mesh_ids"]]
    manifest["spm"] = str(spm_path)
    manifest["spm_action"] = action
    manifest["material_name"] = group_results[0]["material"] if len(group_results) == 1 else None
    manifest["speedtree_material_groups"] = group_results
    manifest["material_id"] = material_id
    manifest["mesh_ids"] = mesh_ids
    manifest["generator_connection"] = generator_connection
    manifest["removed_stale_spm_assets"] = cleanup
    manifest["target_manifest"] = str(target_manifest_path(target_spm))
    Path(manifest_path).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    per_target_manifest_path = target_manifest_path(target_spm)
    per_target_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    per_target_manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    write_scope_manifest(target_spm.parent, manifest, target_spm)
    # Keep a scope identity record without a target suffix so copied blends can
    # be detected before any particular target's update begins.
    write_scope_manifest(target_spm.parent, manifest)
    return (
        spm_path,
        per_target_manifest_path,
        exported_meshes,
        action,
        material_id,
        mesh_ids,
        group_results,
        cleanup,
    )


def export_or_update_speedtree_spm_path(
    props,
    target_spm,
    *,
    atlas_asset_name=None,
    source_material_names=None,
    source_material_ids=None,
    allow_create=False,
):
    """Export/update one target SPM as an all-or-nothing SPM transaction."""
    target_spm = Path(target_spm)
    existed = target_spm.exists()
    original_bytes = target_spm.read_bytes() if existed else None
    try:
        return _export_or_update_speedtree_spm_path_impl(
            props,
            target_spm,
            atlas_asset_name=atlas_asset_name,
            source_material_names=source_material_names,
            source_material_ids=source_material_ids,
            allow_create=allow_create,
        )
    except Exception:
        try:
            if existed:
                target_spm.write_bytes(original_bytes)
            elif target_spm.exists():
                target_spm.unlink()
        except OSError as restore_exc:
            raise RuntimeError(
                f"SPM update failed and transaction restore also failed for {target_spm}: {restore_exc}"
            ) from restore_exc
        raise


def export_or_update_speedtree_spm_targets(props):
    targets = speedtree_spm_targets(props)
    if not targets:
        raise RuntimeError("Add at least one target SPM.")

    source_mapping = speedtree_source_material_mapping(props)
    atlas_asset_name = str(getattr(props, "speedtree_atlas_asset_name", "") or "").strip() or None
    allow_create = bool(getattr(props, "speedtree_create_missing_spm", False))
    results = []
    for target_spm in targets:
        source_request = source_mapping.get(normalized_target_key(target_spm), {})
        spm_path, manifest_path, exported_meshes, action, material_id, mesh_ids, material_groups, cleanup = export_or_update_speedtree_spm_path(
            props,
            target_spm,
            atlas_asset_name=atlas_asset_name,
            source_material_names=source_request.get("source_material_names"),
            source_material_ids=source_request.get("source_material_ids"),
            allow_create=allow_create,
        )
        manifest = read_json_file(manifest_path, {})
        results.append(
            {
                "spm_path": spm_path,
                "manifest_path": manifest_path,
                "exported_meshes": exported_meshes,
                "action": action,
                "material_id": material_id,
                "mesh_ids": mesh_ids,
                "material_groups": material_groups,
                "cleanup": cleanup,
                "generator_connection": manifest.get("generator_connection", {}),
            }
        )
    return results

